language: python
python:
    - "3.6"

notifications:
    email: false

services:
    - docker

install:
    - pip install flake8
    - docker build . -t baselines-test

script:
<<<<<<< HEAD
    - flake8 --select=F stable_baselines/common
    - docker run --env CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN baselines-test sh -c 'pytest --cov-config .coveragerc --cov-report term --cov-report xml --cov=. && python-codacy-coverage -r coverage.xml --token=$CODACY_PROJECT_TOKEN'
=======
    - flake8 --select=F baselines/common
    - docker run --ipc=host --env CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN baselines-test sh -c 'pytest --cov-config .coveragerc --cov-report term --cov-report xml --cov=. && python-codacy-coverage -r coverage.xml --token=$CODACY_PROJECT_TOKEN'
>>>>>>> refactoring
