language: python
python:
    - "3.5"

notifications:
    email: false

services:
    - docker

install:
    - docker build . -t baselines-test

script:
    - docker run --env CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN baselines-test sh -c 'pytest --cov-config .coveragerc --cov-report term --cov-report xml --cov=. -v && python-codacy-coverage -r coverage.xml --token=$CODACY_PROJECT_TOKEN'
